### ISSUE TITLE
Add a quick explanation of what sort does before the first example

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/sorting-readme#14]
I want the reader to get better at given an explanation of a method, understand how it works without seeing an example. I think of it like sight reading. 

So before that first long example of the sort method just say something like "The sort method yields to a block with two elements. That block is the comparator, so it should compare the two elements and return 0 if they are the same, -1 if the first is less then the second, and 1 if the first is greater then the second"

**Comment by sullysaurus** [comment]
Updated.
